USE DATABASE DB_CASE02;
USE SCHEMA PUBLIC;

SELECT
    (SELECT COUNT(*) FROM GOLD_LANE_KPIS) AS lane_rows,
    (SELECT COUNT(*) FROM GOLD_CUSTOMER_MONTHLY_KPIS) AS customer_rows,
    (SELECT COUNT(*) FROM GOLD_LATEST_SHIPMENT_EVENT_STATUS) AS event_rows;

SELECT * FROM GOLD_LANE_KPIS LIMIT 10;
SELECT * FROM GOLD_CUSTOMER_MONTHLY_KPIS LIMIT 10;
SELECT * FROM GOLD_LATEST_SHIPMENT_EVENT_STATUS LIMIT 10;
